package co.ke.bsl.pojo;
// Generated Dec 15, 2015 12:42:43 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Accounts generated by hbm2java
 */

public class Account  implements java.io.Serializable {


     private Integer id;
     private Customer customer;
     private Double availableBal;
     private Double actualBal;
     private Double lockedBal;
     private Date transactionTime;
     private Set<Accountingentries> accountingentrieses = new HashSet<Accountingentries>(0);

    public Account() {
    }

    public Account(Customer customer, Double availableBal, Double actualBal, Double lockedBal, Date transactionTime, Set<Accountingentries> accountingentrieses) {
       this.customer = customer;
       this.availableBal = availableBal;
       this.actualBal = actualBal;
       this.lockedBal = lockedBal;
       this.transactionTime = transactionTime;
       this.accountingentrieses = accountingentrieses;
    }
   
    

}


