package co.ke.bsl.pojo;
// Generated Dec 15, 2015 12:42:43 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Accountingentries generated by hbm2java
 */

public class Accountingentries  implements java.io.Serializable {


     private Integer id;
     private Account accounts;
     private Transaction transactions;
     private Double debit;
     private Double credit;
     private Double amount;
     private Boolean status;
     private String description;
     private Date transactionTime;

    public Accountingentries() {
    }

    public Accountingentries(Account accounts, Transaction transactions, Double debit, Double credit, Double amount, Boolean status, String description, Date transactionTime) {
       this.accounts = accounts;
       this.transactions = transactions;
       this.debit = debit;
       this.credit = credit;
       this.amount = amount;
       this.status = status;
       this.description = description;
       this.transactionTime = transactionTime;
    }

	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return the accounts
	 */
	public Account getAccounts() {
		return accounts;
	}

	/**
	 * @param accounts the accounts to set
	 */
	public void setAccounts(Account accounts) {
		this.accounts = accounts;
	}

	/**
	 * @return the transactions
	 */
	public Transaction getTransactions() {
		return transactions;
	}

	/**
	 * @param transactions the transactions to set
	 */
	public void setTransactions(Transaction transactions) {
		this.transactions = transactions;
	}

	/**
	 * @return the debit
	 */
	public Double getDebit() {
		return debit;
	}

	/**
	 * @param debit the debit to set
	 */
	public void setDebit(Double debit) {
		this.debit = debit;
	}

	/**
	 * @return the credit
	 */
	public Double getCredit() {
		return credit;
	}

	/**
	 * @param credit the credit to set
	 */
	public void setCredit(Double credit) {
		this.credit = credit;
	}

	/**
	 * @return the amount
	 */
	public Double getAmount() {
		return amount;
	}

	/**
	 * @param amount the amount to set
	 */
	public void setAmount(Double amount) {
		this.amount = amount;
	}

	/**
	 * @return the status
	 */
	public Boolean getStatus() {
		return status;
	}

	/**
	 * @param status the status to set
	 */
	public void setStatus(Boolean status) {
		this.status = status;
	}

	/**
	 * @return the description
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * @param description the description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * @return the transactionTime
	 */
	public Date getTransactionTime() {
		return transactionTime;
	}

	/**
	 * @param transactionTime the transactionTime to set
	 */
	public void setTransactionTime(Date transactionTime) {
		this.transactionTime = transactionTime;
	}
   
    

}


