package co.ke.bsl.pojo;

// Generated Dec 15, 2015 12:42:43 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */

public class Customer implements java.io.Serializable {

	private Integer id;
	private SystemAdmin systemAdmin;
	private String firstName;
	private String lastName;
	private String countyName;
	private String subCountyName;
	private String idNo;
	private String emailAddress;
	private String password;
	private Date dateCreated;
	private String  msisdn;
	private Date lastLogIn;
	private Integer countyId;
	private Integer subCountyId;
	private Integer agentId;
	private String physicalAddress;
	private Date lastPasswordChange;
	private Integer status;
	private String intrash;
	private Integer groupId;
	private Integer loanID;
	private  Integer lID;
	private double finalApprovedLoanAmt;
	private double interestLoanAmt;
	private double installmentLoanAmt;
	private double loanBalance;
	private double savingAmount;
	
	private double amount;
	private List<String> savingType;
	private Set<LoanGuarantor> loanguarantors = new HashSet<LoanGuarantor>(0);
	private Set<Loan> loanses = new HashSet<Loan>(0);
	private Set<Account> accountses = new HashSet<Account>(0);
	private Set<Fundsallocation> fundsallocations = new HashSet<Fundsallocation>(
			0);
	private Set<Saving> savingses = new HashSet<Saving>(0);

	public Customer() {
	}

	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * @param id
	 *            the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return the systemAdmin
	 */
	public SystemAdmin getSystemAdmin() {
		return systemAdmin;
	}

	/**
	 * @param systemAdmin
	 *            the systemAdmin to set
	 */
	public void setSystemAdmin(SystemAdmin systemAdmin) {
		this.systemAdmin = systemAdmin;
	}

	/**
	 * @return the firstName
	 */
	public String getFirstName() {
		return firstName;
	}

	/**
	 * @param firstName
	 *            the firstName to set
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	/**
	 * @return the lastName
	 */
	public String getLastName() {
		return lastName;
	}

	/**
	 * @param lastName
	 *            the lastName to set
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	/**
	 * @return the emailAddress
	 */
	public String getEmailAddress() {
		return emailAddress;
	}

	/**
	 * @param emailAddress
	 *            the emailAddress to set
	 */
	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	/**
	 * @return the password
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * @param password
	 *            the password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * @return the dateCreated
	 */
	public Date getDateCreated() {
		return dateCreated;
	}

	/**
	 * @param dateCreated
	 *            the dateCreated to set
	 */
	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	/**
	 * @return the msisdn
	 */
	public String getMsisdn() {
		return msisdn;
	}

	/**
	 * @param msisdn
	 *            the msisdn to set
	 */
	public void setMsisdn(String msisdn) {
		this.msisdn = msisdn;
	}

	/**
	 * @return the lastLogIn
	 */
	public Date getLastLogIn() {
		return lastLogIn;
	}

	/**
	 * @param lastLogIn
	 *            the lastLogIn to set
	 */
	public void setLastLogIn(Date lastLogIn) {
		this.lastLogIn = lastLogIn;
	}

	/**
	 * @return the lastPasswordChange
	 */
	public Date getLastPasswordChange() {
		return lastPasswordChange;
	}

	/**
	 * @param lastPasswordChange
	 *            the lastPasswordChange to set
	 */
	public void setLastPasswordChange(Date lastPasswordChange) {
		this.lastPasswordChange = lastPasswordChange;
	}

	/**
	 * @return the status
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * @param status
	 *            the status to set
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * @return the intrash
	 */
	public String getIntrash() {
		return intrash;
	}

	/**
	 * @param intrash
	 *            the intrash to set
	 */
	public void setIntrash(String intrash) {
		this.intrash = intrash;
	}

	/**
	 * @return the loanguarantors
	 */
	public Set<LoanGuarantor> getLoanguarantors() {
		return loanguarantors;
	}

	/**
	 * @param loanguarantors
	 *            the loanguarantors to set
	 */
	public void setLoanguarantors(Set<LoanGuarantor> loanguarantors) {
		this.loanguarantors = loanguarantors;
	}

	/**
	 * @return the loanses
	 */
	public Set<Loan> getLoanses() {
		return loanses;
	}

	/**
	 * @param loanses
	 *            the loanses to set
	 */
	public void setLoanses(Set<Loan> loanses) {
		this.loanses = loanses;
	}

	/**
	 * @return the accountses
	 */
	public Set<Account> getAccountses() {
		return accountses;
	}

	/**
	 * @param accountses
	 *            the accountses to set
	 */
	public void setAccountses(Set<Account> accountses) {
		this.accountses = accountses;
	}

	/**
	 * @return the fundsallocations
	 */
	public Set<Fundsallocation> getFundsallocations() {
		return fundsallocations;
	}

	/**
	 * @param fundsallocations
	 *            the fundsallocations to set
	 */
	public void setFundsallocations(Set<Fundsallocation> fundsallocations) {
		this.fundsallocations = fundsallocations;
	}

	/**
	 * @return the savingses
	 */
	public Set<Saving> getSavingses() {
		return savingses;
	}

	/**
	 * @param savingses
	 *            the savingses to set
	 */
	public void setSavingses(Set<Saving> savingses) {
		this.savingses = savingses;
	}

	/**
	 * @return the idNo
	 */
	public String getIdNo() {
		return idNo;
	}

	/**
	 * @param idNo the idNo to set
	 */
	public void setIdNo(String idNo) {
		this.idNo = idNo;
	}

	/**
	 * @return the countyId
	 */
	public Integer getCountyId() {
		return countyId;
	}

	/**
	 * @param countyId the countyId to set
	 */
	public void setCountyId(Integer countyId) {
		this.countyId = countyId;
	}

	/**
	 * @return the subCountyId
	 */
	public Integer getSubCountyId() {
		return subCountyId;
	}

	/**
	 * @param subCountyId the subCountyId to set
	 */
	public void setSubCountyId(Integer subCountyId) {
		this.subCountyId = subCountyId;
	}

	/**
	 * @return the agentId
	 */
	public Integer getAgentId() {
		return agentId;
	}

	/**
	 * @param agentId the agentId to set
	 */
	public void setAgentId(Integer agentId) {
		this.agentId = agentId;
	}

	/**
	 * @return the physicalAddress
	 */
	public String getPhysicalAddress() {
		return physicalAddress;
	}

	/**
	 * @param physicalAddress the physicalAddress to set
	 */
	public void setPhysicalAddress(String physicalAddress) {
		this.physicalAddress = physicalAddress;
	}

	/**
	 * @return the countyName
	 */
	public String getCountyName() {
		return countyName;
	}

	/**
	 * @param countyName the countyName to set
	 */
	public void setCountyName(String countyName) {
		this.countyName = countyName;
	}

	/**
	 * @return the subCountyName
	 */
	public String getSubCountyName() {
		return subCountyName;
	}

	/**
	 * @param subCountyName the subCountyName to set
	 */
	public void setSubCountyName(String subCountyName) {
		this.subCountyName = subCountyName;
	}

	/**
	 * @return the groupId
	 */
	public Integer getGroupId() {
		return groupId;
	}

	/**
	 * @param groupId the groupId to set
	 */
	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	/**
	 * @return the loanID
	 */
	public Integer getLoanID() {
		return loanID;
	}

	/**
	 * @param loanID the loanID to set
	 */
	public void setLoanID(Integer loanID) {
		this.loanID = loanID;
	}

	/**
	 * @return the amount
	 */
	public double getAmount() {
		return amount;
	}

	/**
	 * @param amount the amount to set
	 */
	public void setAmount(double amount) {
		this.amount = amount;
	}

	/**
	 * @return the savingType
	 */
	public List<String> getSavingType() {
		return savingType;
	}

	/**
	 * @param savingType the savingType to set
	 */
	public void setSavingType(List<String> savingType) {
		this.savingType = savingType;
	}

	/**
	 * @return the finalApprovedLoanAmt
	 */
	public double getFinalApprovedLoanAmt() {
		return finalApprovedLoanAmt;
	}

	/**
	 * @param finalApprovedLoanAmt the finalApprovedLoanAmt to set
	 */
	public void setFinalApprovedLoanAmt(double finalApprovedLoanAmt) {
		this.finalApprovedLoanAmt = finalApprovedLoanAmt;
	}

	/**
	 * @return the interestLoanAmt
	 */
	public double getInterestLoanAmt() {
		return interestLoanAmt;
	}

	/**
	 * @param interestLoanAmt the interestLoanAmt to set
	 */
	public void setInterestLoanAmt(double interestLoanAmt) {
		this.interestLoanAmt = interestLoanAmt;
	}

	/**
	 * @return the installmentLoanAmt
	 */
	public double getInstallmentLoanAmt() {
		return installmentLoanAmt;
	}

	/**
	 * @param installmentLoanAmt the installmentLoanAmt to set
	 */
	public void setInstallmentLoanAmt(double installmentLoanAmt) {
		this.installmentLoanAmt = installmentLoanAmt;
	}

	/**
	 * @return the loanBalance
	 */
	public double getLoanBalance() {
		return loanBalance;
	}

	/**
	 * @param loanBalance the loanBalance to set
	 */
	public void setLoanBalance(double loanBalance) {
		this.loanBalance = loanBalance;
	}

	/**
	 * @return the savingAmount
	 */
	public double getSavingAmount() {
		return savingAmount;
	}

	/**
	 * @param savingAmount the savingAmount to set
	 */
	public void setSavingAmount(double savingAmount) {
		this.savingAmount = savingAmount;
	}

	/**
	 * @return the lID
	 */
	public Integer getlID() {
		return lID;
	}

	/**
	 * @param lID the lID to set
	 */
	public void setlID(Integer lID) {
		this.lID = lID;
	}

	

}
