package co.ke.bsl.pojo;
// Generated Dec 15, 2015 12:42:43 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Groups generated by hbm2java
 */

public class Group  implements java.io.Serializable {


     private Integer id;
     private String groupName;
     private Date dateCreated;

    public Group() {
    }

    public Group(String groupName, Date dateCreated) {
       this.groupName = groupName;
       this.dateCreated = dateCreated;
    }
   
     
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
   
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }




}


