package co.ke.bsl.pojo;
// Generated Dec 16, 2015 12:26:09 PM by Hibernate Tools 4.3.1



/**
 * Loanguarantor generated by hbm2java
 */

public class LoanGuarantor  implements java.io.Serializable {


     private Integer id;
     private Customer customer;
     private Loan loan;
     private String msisdn;

    public LoanGuarantor() {
    }

    public LoanGuarantor(Customer customer, Loan loan, String msisdn) {
       this.customer = customer;
       this.loan = loan;
       this.msisdn = msisdn;
    }

	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return the customer
	 */
	public Customer getCustomer() {
		return customer;
	}

	/**
	 * @param customer the customer to set
	 */
	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	/**
	 * @return the loan
	 */
	public Loan getLoan() {
		return loan;
	}

	/**
	 * @param loan the loan to set
	 */
	public void setLoan(Loan loan) {
		this.loan = loan;
	}

	/**
	 * @return the msisdn
	 */
	public String getMsisdn() {
		return msisdn;
	}

	/**
	 * @param msisdn the msisdn to set
	 */
	public void setMsisdn(String msisdn) {
		this.msisdn = msisdn;
	}
   
     


}


