package co.ke.bsl.pojo;
// Generated Dec 16, 2015 12:26:09 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LoanType generated by hbm2java
 */

public class LoanType  implements java.io.Serializable {


     private Integer id;
     private String loanProduct;
     private Date createDate;
     private int createdBy;
     private Date txnDate;
     private boolean approved;
     private Integer approvedBy;
     private Date approvedDate;
     private boolean active;
     private boolean defaultProduct;
     private double maxAmount;
     private boolean reducingBal;
     private int maxDuration;
     private Set<Loan> loans = new HashSet<Loan>(0);

    public LoanType() {
    }

	
    public LoanType(String loanProduct, Date createDate, int createdBy, Date txnDate, boolean approved, boolean active, boolean defaultProduct, double maxAmount, boolean reducingBal, int maxDuration) {
        this.loanProduct = loanProduct;
        this.createDate = createDate;
        this.createdBy = createdBy;
        this.txnDate = txnDate;
        this.approved = approved;
        this.active = active;
        this.defaultProduct = defaultProduct;
        this.maxAmount = maxAmount;
        this.reducingBal = reducingBal;
        this.maxDuration = maxDuration;
    }
    public LoanType(String loanProduct, Date createDate, int createdBy, Date txnDate, boolean approved, Integer approvedBy, Date approvedDate, boolean active, boolean defaultProduct, double maxAmount, boolean reducingBal, int maxDuration, Set<Loan> loans) {
       this.loanProduct = loanProduct;
       this.createDate = createDate;
       this.createdBy = createdBy;
       this.txnDate = txnDate;
       this.approved = approved;
       this.approvedBy = approvedBy;
       this.approvedDate = approvedDate;
       this.active = active;
       this.defaultProduct = defaultProduct;
       this.maxAmount = maxAmount;
       this.reducingBal = reducingBal;
       this.maxDuration = maxDuration;
       this.loans = loans;
    }


	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}


	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}


	/**
	 * @return the loanProduct
	 */
	public String getLoanProduct() {
		return loanProduct;
	}


	/**
	 * @param loanProduct the loanProduct to set
	 */
	public void setLoanProduct(String loanProduct) {
		this.loanProduct = loanProduct;
	}


	/**
	 * @return the createDate
	 */
	public Date getCreateDate() {
		return createDate;
	}


	/**
	 * @param createDate the createDate to set
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}


	/**
	 * @return the createdBy
	 */
	public int getCreatedBy() {
		return createdBy;
	}


	/**
	 * @param createdBy the createdBy to set
	 */
	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}


	/**
	 * @return the txnDate
	 */
	public Date getTxnDate() {
		return txnDate;
	}


	/**
	 * @param txnDate the txnDate to set
	 */
	public void setTxnDate(Date txnDate) {
		this.txnDate = txnDate;
	}


	/**
	 * @return the approved
	 */
	public boolean isApproved() {
		return approved;
	}


	/**
	 * @param approved the approved to set
	 */
	public void setApproved(boolean approved) {
		this.approved = approved;
	}


	/**
	 * @return the approvedBy
	 */
	public Integer getApprovedBy() {
		return approvedBy;
	}


	/**
	 * @param approvedBy the approvedBy to set
	 */
	public void setApprovedBy(Integer approvedBy) {
		this.approvedBy = approvedBy;
	}


	/**
	 * @return the approvedDate
	 */
	public Date getApprovedDate() {
		return approvedDate;
	}


	/**
	 * @param approvedDate the approvedDate to set
	 */
	public void setApprovedDate(Date approvedDate) {
		this.approvedDate = approvedDate;
	}


	/**
	 * @return the active
	 */
	public boolean isActive() {
		return active;
	}


	/**
	 * @param active the active to set
	 */
	public void setActive(boolean active) {
		this.active = active;
	}


	/**
	 * @return the defaultProduct
	 */
	public boolean isDefaultProduct() {
		return defaultProduct;
	}


	/**
	 * @param defaultProduct the defaultProduct to set
	 */
	public void setDefaultProduct(boolean defaultProduct) {
		this.defaultProduct = defaultProduct;
	}


	/**
	 * @return the maxAmount
	 */
	public double getMaxAmount() {
		return maxAmount;
	}


	/**
	 * @param maxAmount the maxAmount to set
	 */
	public void setMaxAmount(double maxAmount) {
		this.maxAmount = maxAmount;
	}


	/**
	 * @return the reducingBal
	 */
	public boolean isReducingBal() {
		return reducingBal;
	}


	/**
	 * @param reducingBal the reducingBal to set
	 */
	public void setReducingBal(boolean reducingBal) {
		this.reducingBal = reducingBal;
	}


	/**
	 * @return the maxDuration
	 */
	public int getMaxDuration() {
		return maxDuration;
	}


	/**
	 * @param maxDuration the maxDuration to set
	 */
	public void setMaxDuration(int maxDuration) {
		this.maxDuration = maxDuration;
	}


	/**
	 * @return the loans
	 */
	public Set<Loan> getLoanes() {
		return loans;
	}


	/**
	 * @param loans the loans to set
	 */
	public void setLoanes(Set<Loan> loans) {
		this.loans = loans;
	}
   
    



}


