package co.ke.bsl.pojo;
// Generated Dec 15, 2015 12:42:43 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Loans generated by hbm2java
 */

public class Loan  implements java.io.Serializable {


     private Integer id;
     private Customer customer;
     private LoanType loanType;
     private SystemAdmin systemsadmin;
     private TransactionType transactionType;
     private Date trxTime;
     private String msisdn;
     private String b2cShortcode;
     private Double amount;
     private Double period;
     private Date timeInitiated;
     private Date timeApproved;
     private String approvalStatus;
     private Double approvedAmount;
     private String sessionId;
     private Double interest;
     private Double totalPlusInterest;
     private Double monthlyInstallments;
     private Integer approvalLevel;
     private Double finalApproval;
     private String loanPaymentStatus;
     private Date approvalDate;
     private String comments;
     private String loanNumber;
     private Date defaultDate;
     private String loanRejectTag;
     private String whitelisted;
     private Date whitelistDate;
     private Set<LoanGuarantor> loanguarantors = new HashSet<LoanGuarantor>(0);
     private Set<Transaction> transactionses = new HashSet<Transaction>(0);
     private Set<Saving> savingses = new HashSet<Saving>(0);

    public Loan() {
    }

    public Loan(Customer customer, LoanType loanType, SystemAdmin systemsadmin, TransactionType transactionType, Date trxTime, String msisdn, String b2cShortcode,
                Double amount, Double period, Date timeInitiated, Date timeApproved,
                String approvalStatus, Double approvedAmount, String sessionId, Double interest,
                Double totalPlusInterest, Double monthlyInstallments, Integer approvalLevel,
                Double finalApproval, String loanPaymentStatus, Date approvalDate,
                String comments, String loanNumber, Date defaultDate, String loanRejectTag,
                String whitelisted, Date whitelistDate, Set<LoanGuarantor> loanguarantors, Set<Transaction> transactionses, Set<Saving> savingses) {
       this.customer = customer;
       this.loanType = loanType;
       this.systemsadmin = systemsadmin;
       this.transactionType = transactionType;
       this.trxTime = trxTime;
       this.msisdn = msisdn;
       this.b2cShortcode = b2cShortcode;
       this.amount = amount;
       this.period = period;
       this.timeInitiated = timeInitiated;
       this.timeApproved = timeApproved;
       this.approvalStatus = approvalStatus;
       this.approvedAmount = approvedAmount;
       this.sessionId = sessionId;
       this.interest = interest;
       this.totalPlusInterest = totalPlusInterest;
       this.monthlyInstallments = monthlyInstallments;
       this.approvalLevel = approvalLevel;
       this.finalApproval = finalApproval;
       this.loanPaymentStatus = loanPaymentStatus;
       this.approvalDate = approvalDate;
       this.comments = comments;
       this.loanNumber = loanNumber;
       this.defaultDate = defaultDate;
       this.loanRejectTag = loanRejectTag;
       this.whitelisted = whitelisted;
       this.whitelistDate = whitelistDate;
       this.loanguarantors = loanguarantors;
       this.transactionses = transactionses;
       this.savingses = savingses;
    }

	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return the customer
	 */
	public Customer getCustomer() {
		return customer;
	}

	/**
	 * @param customer the customer to set
	 */
	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	/**
	 * @return the loanType
	 */
	public LoanType getLoanType() {
		return loanType;
	}

	/**
	 * @param loanType the loanType to set
	 */
	public void setLoanType(LoanType loanType) {
		this.loanType = loanType;
	}

	/**
	 * @return the systemsadmin
	 */
	public SystemAdmin getSystemsadmin() {
		return systemsadmin;
	}

	/**
	 * @param systemsadmin the systemsadmin to set
	 */
	public void setSystemsadmin(SystemAdmin systemsadmin) {
		this.systemsadmin = systemsadmin;
	}

	/**
	 * @return the transactionType
	 */
	public TransactionType getTransactionType() {
		return transactionType;
	}

	/**
	 * @param transactionType the transactionType to set
	 */
	public void setTransactionType(TransactionType transactionType) {
		this.transactionType = transactionType;
	}

	/**
	 * @return the trxTime
	 */
	public Date getTrxTime() {
		return trxTime;
	}

	/**
	 * @param trxTime the trxTime to set
	 */
	public void setTrxTime(Date trxTime) {
		this.trxTime = trxTime;
	}

	/**
	 * @return the msisdn
	 */
	public String getMsisdn() {
		return msisdn;
	}

	/**
	 * @param msisdn the msisdn to set
	 */
	public void setMsisdn(String msisdn) {
		this.msisdn = msisdn;
	}

	/**
	 * @return the b2cShortcode
	 */
	public String getB2cShortcode() {
		return b2cShortcode;
	}

	/**
	 * @param b2cShortcode the b2cShortcode to set
	 */
	public void setB2cShortcode(String b2cShortcode) {
		this.b2cShortcode = b2cShortcode;
	}

	/**
	 * @return the amount
	 */
	public Double getAmount() {
		return amount;
	}

	/**
	 * @param amount the amount to set
	 */
	public void setAmount(Double amount) {
		this.amount = amount;
	}

	/**
	 * @return the period
	 */
	public Double getPeriod() {
		return period;
	}

	/**
	 * @param period the period to set
	 */
	public void setPeriod(Double period) {
		this.period = period;
	}

	/**
	 * @return the timeInitiated
	 */
	public Date getTimeInitiated() {
		return timeInitiated;
	}

	/**
	 * @param timeInitiated the timeInitiated to set
	 */
	public void setTimeInitiated(Date timeInitiated) {
		this.timeInitiated = timeInitiated;
	}

	/**
	 * @return the timeApproved
	 */
	public Date getTimeApproved() {
		return timeApproved;
	}

	/**
	 * @param timeApproved the timeApproved to set
	 */
	public void setTimeApproved(Date timeApproved) {
		this.timeApproved = timeApproved;
	}

	/**
	 * @return the approvalStatus
	 */
	public String getApprovalStatus() {
		return approvalStatus;
	}

	/**
	 * @param approvalStatus the approvalStatus to set
	 */
	public void setApprovalStatus(String approvalStatus) {
		this.approvalStatus = approvalStatus;
	}

	/**
	 * @return the approvedAmount
	 */
	public Double getApprovedAmount() {
		return approvedAmount;
	}

	/**
	 * @param approvedAmount the approvedAmount to set
	 */
	public void setApprovedAmount(Double approvedAmount) {
		this.approvedAmount = approvedAmount;
	}

	/**
	 * @return the sessionId
	 */
	public String getSessionId() {
		return sessionId;
	}

	/**
	 * @param sessionId the sessionId to set
	 */
	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	/**
	 * @return the interest
	 */
	public Double getInterest() {
		return interest;
	}

	/**
	 * @param interest the interest to set
	 */
	public void setInterest(Double interest) {
		this.interest = interest;
	}

	/**
	 * @return the totalPlusInterest
	 */
	public Double getTotalPlusInterest() {
		return totalPlusInterest;
	}

	/**
	 * @param totalPlusInterest the totalPlusInterest to set
	 */
	public void setTotalPlusInterest(Double totalPlusInterest) {
		this.totalPlusInterest = totalPlusInterest;
	}

	/**
	 * @return the monthlyInstallments
	 */
	public Double getMonthlyInstallments() {
		return monthlyInstallments;
	}

	/**
	 * @param monthlyInstallments the monthlyInstallments to set
	 */
	public void setMonthlyInstallments(Double monthlyInstallments) {
		this.monthlyInstallments = monthlyInstallments;
	}

	/**
	 * @return the approvalLevel
	 */
	public Integer getApprovalLevel() {
		return approvalLevel;
	}

	/**
	 * @param approvalLevel the approvalLevel to set
	 */
	public void setApprovalLevel(Integer approvalLevel) {
		this.approvalLevel = approvalLevel;
	}

	/**
	 * @return the finalApproval
	 */
	public Double getFinalApproval() {
		return finalApproval;
	}

	/**
	 * @param finalApproval the finalApproval to set
	 */
	public void setFinalApproval(Double finalApproval) {
		this.finalApproval = finalApproval;
	}

	/**
	 * @return the loanPaymentStatus
	 */
	public String getLoanPaymentStatus() {
		return loanPaymentStatus;
	}

	/**
	 * @param loanPaymentStatus the loanPaymentStatus to set
	 */
	public void setLoanPaymentStatus(String loanPaymentStatus) {
		this.loanPaymentStatus = loanPaymentStatus;
	}

	/**
	 * @return the approvalDate
	 */
	public Date getApprovalDate() {
		return approvalDate;
	}

	/**
	 * @param approvalDate the approvalDate to set
	 */
	public void setApprovalDate(Date approvalDate) {
		this.approvalDate = approvalDate;
	}

	/**
	 * @return the comments
	 */
	public String getComments() {
		return comments;
	}

	/**
	 * @param comments the comments to set
	 */
	public void setComments(String comments) {
		this.comments = comments;
	}

	/**
	 * @return the loanNumber
	 */
	public String getLoanNumber() {
		return loanNumber;
	}

	/**
	 * @param loanNumber the loanNumber to set
	 */
	public void setLoanNumber(String loanNumber) {
		this.loanNumber = loanNumber;
	}

	/**
	 * @return the defaultDate
	 */
	public Date getDefaultDate() {
		return defaultDate;
	}

	/**
	 * @param defaultDate the defaultDate to set
	 */
	public void setDefaultDate(Date defaultDate) {
		this.defaultDate = defaultDate;
	}

	/**
	 * @return the loanRejectTag
	 */
	public String getLoanRejectTag() {
		return loanRejectTag;
	}

	/**
	 * @param loanRejectTag the loanRejectTag to set
	 */
	public void setLoanRejectTag(String loanRejectTag) {
		this.loanRejectTag = loanRejectTag;
	}

	/**
	 * @return the whitelisted
	 */
	public String getWhitelisted() {
		return whitelisted;
	}

	/**
	 * @param whitelisted the whitelisted to set
	 */
	public void setWhitelisted(String whitelisted) {
		this.whitelisted = whitelisted;
	}

	/**
	 * @return the whitelistDate
	 */
	public Date getWhitelistDate() {
		return whitelistDate;
	}

	/**
	 * @param whitelistDate the whitelistDate to set
	 */
	public void setWhitelistDate(Date whitelistDate) {
		this.whitelistDate = whitelistDate;
	}

	/**
	 * @return the loanguarantors
	 */
	public Set<LoanGuarantor> getLoanguarantors() {
		return loanguarantors;
	}

	/**
	 * @param loanguarantors the loanguarantors to set
	 */
	public void setLoanguarantors(Set<LoanGuarantor> loanguarantors) {
		this.loanguarantors = loanguarantors;
	}

	/**
	 * @return the transactionses
	 */
	public Set<Transaction> getTransactionses() {
		return transactionses;
	}

	/**
	 * @param transactionses the transactionses to set
	 */
	public void setTransactionses(Set<Transaction> transactionses) {
		this.transactionses = transactionses;
	}

	/**
	 * @return the savingses
	 */
	public Set<Saving> getSavingses() {
		return savingses;
	}

	/**
	 * @param savingses the savingses to set
	 */
	public void setSavingses(Set<Saving> savingses) {
		this.savingses = savingses;
	}
   
}
