package co.ke.bsl.pojo;
// Generated Dec 15, 2015 12:42:43 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */

public class Role  implements java.io.Serializable {


     private Integer id;
     private String roleName;
     private Date dateCreated;
     private Set<PermissionMap> permissionsmaps = new HashSet<PermissionMap>(0);
     private Set<SystemAdmin> systemsadmins = new HashSet<SystemAdmin>(0);

    public Role() {
    }

    public Role(String roleName, Date dateCreated, Set<PermissionMap> permissionsmaps, Set<SystemAdmin> systemsadmins) {
       this.roleName = roleName;
       this.dateCreated = dateCreated;
       this.permissionsmaps = permissionsmaps;
       this.systemsadmins = systemsadmins;
    }

	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return the roleName
	 */
	public String getRoleName() {
		return roleName;
	}

	/**
	 * @param roleName the roleName to set
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	/**
	 * @return the dateCreated
	 */
	public Date getDateCreated() {
		return dateCreated;
	}

	/**
	 * @param dateCreated the dateCreated to set
	 */
	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	/**
	 * @return the permissionsmaps
	 */
	public Set<PermissionMap> getPermissionsmaps() {
		return permissionsmaps;
	}

	/**
	 * @param permissionsmaps the permissionsmaps to set
	 */
	public void setPermissionsmaps(Set<PermissionMap> permissionsmaps) {
		this.permissionsmaps = permissionsmaps;
	}

	/**
	 * @return the systemsadmins
	 */
	public Set<SystemAdmin> getSystemsadmins() {
		return systemsadmins;
	}

	/**
	 * @param systemsadmins the systemsadmins to set
	 */
	public void setSystemsadmins(Set<SystemAdmin> systemsadmins) {
		this.systemsadmins = systemsadmins;
	}
   
   


}


