package co.ke.bsl.pojo;
// Generated Dec 16, 2015 12:26:09 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Savings generated by hbm2java
 */

public class Saving  implements java.io.Serializable {


     private Integer id;
     private Customer customer;
     private Loan loan;
     private SavingType savingstype;
     private TransactionType transactionstype;
     private Date trxTime;
     private String msisdn;
     private String c2bShortcode;
     private Double amount;
     private String accountId;
     private Date timeInitiated;
     private Date timeCompleted;
     private String referenceId;
     private String sessionId;
     private Integer transactionId;
     private String transactionDesc;
     private String transactionStatus;

    public Saving() {
    }

	
    public Saving(SavingType savingstype, TransactionType transactionstype) {
        this.savingstype = savingstype;
        this.transactionstype = transactionstype;
    }
    public Saving(Customer customer, Loan loan, SavingType savingstype, TransactionType transactionstype, Date trxTime, String msisdn, String c2bShortcode, Double amount, String accountId, Date timeInitiated, Date timeCompleted, String referenceId, String sessionId, Integer transactionId, String transactionDesc, String transactionStatus) {
       this.customer = customer;
       this.loan = loan;
       this.savingstype = savingstype;
       this.transactionstype = transactionstype;
       this.trxTime = trxTime;
       this.msisdn = msisdn;
       this.c2bShortcode = c2bShortcode;
       this.amount = amount;
       this.accountId = accountId;
       this.timeInitiated = timeInitiated;
       this.timeCompleted = timeCompleted;
       this.referenceId = referenceId;
       this.sessionId = sessionId;
       this.transactionId = transactionId;
       this.transactionDesc = transactionDesc;
       this.transactionStatus = transactionStatus;
    }
   


}


