package co.ke.bsl.pojo;
// Generated Dec 16, 2015 12:26:09 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Savingstype generated by hbm2java
 */

public class SavingType  implements java.io.Serializable {


     private Integer id;
     private String savingsType;
     private Date createDate;
     private int createdBy;
     private Date txnDate;
     private boolean approved;
     private Integer approvedBy;
     private Date approvedDate;
     private boolean active;
     private Set<Saving> savingses = new HashSet<Saving>(0);

    public SavingType() {
    }

	
    public SavingType(String savingsType, Date createDate, int createdBy, Date txnDate, boolean approved, boolean active) {
        this.savingsType = savingsType;
        this.createDate = createDate;
        this.createdBy = createdBy;
        this.txnDate = txnDate;
        this.approved = approved;
        this.active = active;
    }
    public SavingType(String savingsType, Date createDate, int createdBy, Date txnDate, boolean approved, Integer approvedBy, Date approvedDate, boolean active, Set<Saving> savingses) {
       this.savingsType = savingsType;
       this.createDate = createDate;
       this.createdBy = createdBy;
       this.txnDate = txnDate;
       this.approved = approved;
       this.approvedBy = approvedBy;
       this.approvedDate = approvedDate;
       this.active = active;
       this.savingses = savingses;
    }


	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}


	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}


	/**
	 * @return the savingsType
	 */
	public String getSavingsType() {
		return savingsType;
	}


	/**
	 * @param savingsType the savingsType to set
	 */
	public void setSavingsType(String savingsType) {
		this.savingsType = savingsType;
	}


	/**
	 * @return the createDate
	 */
	public Date getCreateDate() {
		return createDate;
	}


	/**
	 * @param createDate the createDate to set
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}


	/**
	 * @return the createdBy
	 */
	public int getCreatedBy() {
		return createdBy;
	}


	/**
	 * @param createdBy the createdBy to set
	 */
	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}


	/**
	 * @return the txnDate
	 */
	public Date getTxnDate() {
		return txnDate;
	}


	/**
	 * @param txnDate the txnDate to set
	 */
	public void setTxnDate(Date txnDate) {
		this.txnDate = txnDate;
	}


	/**
	 * @return the approved
	 */
	public boolean isApproved() {
		return approved;
	}


	/**
	 * @param approved the approved to set
	 */
	public void setApproved(boolean approved) {
		this.approved = approved;
	}


	/**
	 * @return the approvedBy
	 */
	public Integer getApprovedBy() {
		return approvedBy;
	}


	/**
	 * @param approvedBy the approvedBy to set
	 */
	public void setApprovedBy(Integer approvedBy) {
		this.approvedBy = approvedBy;
	}


	/**
	 * @return the approvedDate
	 */
	public Date getApprovedDate() {
		return approvedDate;
	}


	/**
	 * @param approvedDate the approvedDate to set
	 */
	public void setApprovedDate(Date approvedDate) {
		this.approvedDate = approvedDate;
	}


	/**
	 * @return the active
	 */
	public boolean isActive() {
		return active;
	}


	/**
	 * @param active the active to set
	 */
	public void setActive(boolean active) {
		this.active = active;
	}


	/**
	 * @return the savingses
	 */
	public Set<Saving> getSavingses() {
		return savingses;
	}


	/**
	 * @param savingses the savingses to set
	 */
	public void setSavingses(Set<Saving> savingses) {
		this.savingses = savingses;
	}
   

}


