package co.ke.bsl.pojo;
// Generated Dec 15, 2015 12:42:43 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Servicecharge generated by hbm2java
 */

public class Servicecharge  implements java.io.Serializable {


     private Integer id;
     private Transaction transaction;
     private Double amount;
     private Date dateCreated;
     private Set<Tariff> tariffsids = new HashSet<Tariff>(0);

    public Servicecharge() {
    }

    public Servicecharge(Transaction transaction, Double amount, Date dateCreated, Set<Tariff> tariffsids) {
       this.transaction = transaction;
       this.amount = amount;
       this.dateCreated = dateCreated;
       this.tariffsids = tariffsids;
    }

	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return the transaction
	 */
	public Transaction getTransaction() {
		return transaction;
	}

	/**
	 * @param transaction the transaction to set
	 */
	public void setTransaction(Transaction transaction) {
		this.transaction = transaction;
	}

	/**
	 * @return the amount
	 */
	public Double getAmount() {
		return amount;
	}

	/**
	 * @param amount the amount to set
	 */
	public void setAmount(Double amount) {
		this.amount = amount;
	}

	/**
	 * @return the dateCreated
	 */
	public Date getDateCreated() {
		return dateCreated;
	}

	/**
	 * @param dateCreated the dateCreated to set
	 */
	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	/**
	 * @return the tariffsids
	 */
	public Set<Tariff> getTariffsids() {
		return tariffsids;
	}

	/**
	 * @param tariffsids the tariffsids to set
	 */
	public void setTariffsids(Set<Tariff> tariffsids) {
		this.tariffsids = tariffsids;
	}
   
     

}


