package co.ke.bsl.pojo;
// Generated Dec 15, 2015 12:42:43 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Systemsadmin generated by hbm2java
 */

public class SystemAdmin  implements java.io.Serializable {


     private Integer id;
     private Role role;
     private SystemAdmin systemsadmin;
     private String firstName;
     private String middleName;
     private String lastName;
     private String emailAddress;
     private String phoneNumber;
     private String userName;
     private String password;
     private Date dateCreated;
     private Integer msisdn;
     private Date lastLogIn;
     private Date lastPasswordChange;
     private boolean status;
     private boolean intrash;
     private Set<SystemAdmin> systemAdminList = new HashSet<SystemAdmin>(0);
     private Set<Customer> customersForCreatedBy = new HashSet<Customer>(0);
     private Set<Loan> loanses = new HashSet<Loan>(0);
     private Set<Customer> customersForApprovedBy = new HashSet<Customer>(0);

    public SystemAdmin() {
    }

	
    public SystemAdmin(Role roles, boolean status, boolean intrash) {
        this.role = roles;
        this.status = status;
        this.intrash = intrash;
    }
    public SystemAdmin(Role roles, SystemAdmin systemsadmin,
                       String firstName, String middleName, String lastName,
                       String emailAddress, String phoneNumber, String userName,
                       String password, Date dateCreated, Integer msisdn, Date lastLogIn,
                       Date lastPasswordChange, boolean status, boolean intrash,
                       Set<SystemAdmin> systemAdminList, Set<Customer> customersForCreatedBy,
                       Set<Loan> loanses, Set<Customer> customersForApprovedBy) {
       this.role = roles;
       this.systemsadmin = systemsadmin;
       this.firstName = firstName;
       this.middleName = middleName;
       this.lastName = lastName;
       this.emailAddress = emailAddress;
       this.phoneNumber = phoneNumber;
       this.userName = userName;
       this.password = password;
       this.dateCreated = dateCreated;
       this.msisdn = msisdn;
       this.lastLogIn = lastLogIn;
       this.lastPasswordChange = lastPasswordChange;
       this.status = status;
       this.intrash = intrash;
       this.systemAdminList = systemAdminList;
       this.customersForCreatedBy = customersForCreatedBy;
       this.loanses = loanses;
       this.customersForApprovedBy = customersForApprovedBy;
    }


	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}


	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}


	/**
	 * @return the role
	 */
	public Role getRole() {
		return role;
	}


	/**
	 * @param role the role to set
	 */
	public void setRole(Role role) {
		this.role = role;
	}


	/**
	 * @return the systemsadmin
	 */
	public SystemAdmin getSystemsadmin() {
		return systemsadmin;
	}


	/**
	 * @param systemsadmin the systemsadmin to set
	 */
	public void setSystemsadmin(SystemAdmin systemsadmin) {
		this.systemsadmin = systemsadmin;
	}


	/**
	 * @return the firstName
	 */
	public String getFirstName() {
		return firstName;
	}


	/**
	 * @param firstName the firstName to set
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}


	/**
	 * @return the middleName
	 */
	public String getMiddleName() {
		return middleName;
	}


	/**
	 * @param middleName the middleName to set
	 */
	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}


	/**
	 * @return the lastName
	 */
	public String getLastName() {
		return lastName;
	}


	/**
	 * @param lastName the lastName to set
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}


	/**
	 * @return the emailAddress
	 */
	public String getEmailAddress() {
		return emailAddress;
	}


	/**
	 * @param emailAddress the emailAddress to set
	 */
	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}


	/**
	 * @return the phoneNumber
	 */
	public String getPhoneNumber() {
		return phoneNumber;
	}


	/**
	 * @param phoneNumber the phoneNumber to set
	 */
	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}


	/**
	 * @return the userName
	 */
	public String getUserName() {
		return userName;
	}


	/**
	 * @param userName the userName to set
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}


	/**
	 * @return the password
	 */
	public String getPassword() {
		return password;
	}


	/**
	 * @param password the password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}


	/**
	 * @return the dateCreated
	 */
	public Date getDateCreated() {
		return dateCreated;
	}


	/**
	 * @param dateCreated the dateCreated to set
	 */
	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}


	/**
	 * @return the msisdn
	 */
	public Integer getMsisdn() {
		return msisdn;
	}


	/**
	 * @param msisdn the msisdn to set
	 */
	public void setMsisdn(Integer msisdn) {
		this.msisdn = msisdn;
	}


	/**
	 * @return the lastLogIn
	 */
	public Date getLastLogIn() {
		return lastLogIn;
	}


	/**
	 * @param lastLogIn the lastLogIn to set
	 */
	public void setLastLogIn(Date lastLogIn) {
		this.lastLogIn = lastLogIn;
	}


	/**
	 * @return the lastPasswordChange
	 */
	public Date getLastPasswordChange() {
		return lastPasswordChange;
	}


	/**
	 * @param lastPasswordChange the lastPasswordChange to set
	 */
	public void setLastPasswordChange(Date lastPasswordChange) {
		this.lastPasswordChange = lastPasswordChange;
	}


	/**
	 * @return the status
	 */
	public boolean isStatus() {
		return status;
	}


	/**
	 * @param status the status to set
	 */
	public void setStatus(boolean status) {
		this.status = status;
	}


	/**
	 * @return the intrash
	 */
	public boolean isIntrash() {
		return intrash;
	}


	/**
	 * @param intrash the intrash to set
	 */
	public void setIntrash(boolean intrash) {
		this.intrash = intrash;
	}


	/**
	 * @return the systemAdminList
	 */
	public Set<SystemAdmin> getSystemAdminList() {
		return systemAdminList;
	}


	/**
	 * @param systemAdminList the systemAdminList to set
	 */
	public void setSystemAdminList(Set<SystemAdmin> systemAdminList) {
		this.systemAdminList = systemAdminList;
	}


	/**
	 * @return the customersForCreatedBy
	 */
	public Set<Customer> getCustomersForCreatedBy() {
		return customersForCreatedBy;
	}


	/**
	 * @param customersForCreatedBy the customersForCreatedBy to set
	 */
	public void setCustomersForCreatedBy(Set<Customer> customersForCreatedBy) {
		this.customersForCreatedBy = customersForCreatedBy;
	}


	/**
	 * @return the loanses
	 */
	public Set<Loan> getLoanses() {
		return loanses;
	}


	/**
	 * @param loanses the loanses to set
	 */
	public void setLoanses(Set<Loan> loanses) {
		this.loanses = loanses;
	}


	/**
	 * @return the customersForApprovedBy
	 */
	public Set<Customer> getCustomersForApprovedBy() {
		return customersForApprovedBy;
	}


	/**
	 * @param customersForApprovedBy the customersForApprovedBy to set
	 */
	public void setCustomersForApprovedBy(Set<Customer> customersForApprovedBy) {
		this.customersForApprovedBy = customersForApprovedBy;
	}
   
    


}


