package co.ke.bsl.pojo;
// Generated Dec 15, 2015 12:42:43 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tariffsid generated by hbm2java
 */

public class Tariff  implements java.io.Serializable {


     private Integer id;
     private Servicecharge servicecharge;
     private String parameterName;
     private String parameterValue;
     private Date dateCreated;

    public Tariff() {
    }

    public Tariff(Servicecharge servicecharge, String parameterName, String parameterValue, Date dateCreated) {
       this.servicecharge = servicecharge;
       this.parameterName = parameterName;
       this.parameterValue = parameterValue;
       this.dateCreated = dateCreated;
    }

	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return the servicecharge
	 */
	public Servicecharge getServicecharge() {
		return servicecharge;
	}

	/**
	 * @param servicecharge the servicecharge to set
	 */
	public void setServicecharge(Servicecharge servicecharge) {
		this.servicecharge = servicecharge;
	}

	/**
	 * @return the parameterName
	 */
	public String getParameterName() {
		return parameterName;
	}

	/**
	 * @param parameterName the parameterName to set
	 */
	public void setParameterName(String parameterName) {
		this.parameterName = parameterName;
	}

	/**
	 * @return the parameterValue
	 */
	public String getParameterValue() {
		return parameterValue;
	}

	/**
	 * @param parameterValue the parameterValue to set
	 */
	public void setParameterValue(String parameterValue) {
		this.parameterValue = parameterValue;
	}

	/**
	 * @return the dateCreated
	 */
	public Date getDateCreated() {
		return dateCreated;
	}

	/**
	 * @param dateCreated the dateCreated to set
	 */
	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}
   
     


}


