package co.ke.bsl.pojo;
// Generated Dec 15, 2015 12:42:43 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Transactions generated by hbm2java
 */

public class Transaction  implements java.io.Serializable {


     private Integer id;
     private Loan loan;
     private String trxId;
     private Date trxTime;
     private String msisdn;
     private String trxType;
     private String c2bShortcode;
     private String b2cShortcode;
     private Double amount;
     private Double commissions;
     private Double serviceCharge;
     private Double trxStatus;
     private String returnCode;
     private String trxDesc;
     private Integer intermediateStatus;
     private String debitParty;
     private String creditParty;
     private String referenceId;
     private Date timeInitiated;
     private Date timeCompleted;
     private Double failCount;
     private Double msgSendingStatus;
     private Double availableFunds;
     private String sessionId;
     private String conversationId;
     private String origConversationId;
     private String upload;
     private Date timeRejected;
     private String clientId;
     private String channel;
     private String accountingAction;
     private Set<Accountingentries> accountingentrieses = new HashSet<Accountingentries>(0);
     private Set<Servicecharge> servicecharges = new HashSet<Servicecharge>(0);
     private Set<TransactionType> transactionstypes = new HashSet<TransactionType>(0);

    public Transaction() {
    }

    public Transaction(Loan loan, String trxId, Date trxTime, String msisdn, String trxType, String c2bShortcode, String b2cShortcode, Double amount, Double commissions, Double serviceCharge, Double trxStatus, String returnCode, String trxDesc, Integer intermediateStatus, String debitParty, String creditParty, String referenceId, Date timeInitiated, Date timeCompleted, Double failCount, Double msgSendingStatus, Double availableFunds, String sessionId, String conversationId, String origConversationId, String upload, Date timeRejected, String clientId, String channel, String accountingAction, Set<Accountingentries> accountingentrieses, Set<Servicecharge> servicecharges, Set<TransactionType> transactionstypes) {
       this.loan = loan;
       this.trxId = trxId;
       this.trxTime = trxTime;
       this.msisdn = msisdn;
       this.trxType = trxType;
       this.c2bShortcode = c2bShortcode;
       this.b2cShortcode = b2cShortcode;
       this.amount = amount;
       this.commissions = commissions;
       this.serviceCharge = serviceCharge;
       this.trxStatus = trxStatus;
       this.returnCode = returnCode;
       this.trxDesc = trxDesc;
       this.intermediateStatus = intermediateStatus;
       this.debitParty = debitParty;
       this.creditParty = creditParty;
       this.referenceId = referenceId;
       this.timeInitiated = timeInitiated;
       this.timeCompleted = timeCompleted;
       this.failCount = failCount;
       this.msgSendingStatus = msgSendingStatus;
       this.availableFunds = availableFunds;
       this.sessionId = sessionId;
       this.conversationId = conversationId;
       this.origConversationId = origConversationId;
       this.upload = upload;
       this.timeRejected = timeRejected;
       this.clientId = clientId;
       this.channel = channel;
       this.accountingAction = accountingAction;
       this.accountingentrieses = accountingentrieses;
       this.servicecharges = servicecharges;
       this.transactionstypes = transactionstypes;
    }
   
     


}


