package co.ke.bsl.pojo;

// Generated Dec 15, 2015 12:42:43 PM by Hibernate Tools 4.3.1

import org.idempiere.webservice.client.base.LoginRequest;

/**
 * Agents generated by hbm2java
 */

public class WholeSaleStockedBrandLocal implements java.io.Serializable {


	private String brand;
	private String priceOf50kgBag;
	private String priceOf24kgBale;
	private String priceOf20kgBale;

	private LoginRequest loginRequest;
	private String AFA_SD_SGR_Surveyshops_ID;
	private String serviceType="CreateWholesaleStockingPricesRangeLocal";

	private String serverRecordID;


	private String shopID;


	public String  localID;

	public String getLocalID() {
		return localID;
	}

	public void setLocalID(String localID) {
		this.localID = localID;
	}

	public String getShopID() {
		return shopID;
	}

	public void setShopID(String shopID) {
		this.shopID = shopID;
	}

	public String getServerRecordID() {
		return serverRecordID;
	}

	public void setServerRecordID(String serverRecordID) {
		this.serverRecordID = serverRecordID;
	}

	public LoginRequest getLoginRequest() {
		return loginRequest;
	}

	public void setLoginRequest(LoginRequest loginRequest) {
		this.loginRequest = loginRequest;
	}

	public String getAFA_SD_SGR_Surveyshops_ID() {
		return AFA_SD_SGR_Surveyshops_ID;
	}

	public void setAFA_SD_SGR_Surveyshops_ID(String AFA_SD_SGR_Surveyshops_ID) {
		this.AFA_SD_SGR_Surveyshops_ID = AFA_SD_SGR_Surveyshops_ID;
	}

	public String getServiceType() {
		return serviceType;
	}

	public void setServiceType(String serviceType) {
		this.serviceType = serviceType;
	}

	public String getBrand() {
		return brand;
	}

	public WholeSaleStockedBrandLocal setBrand(String brand) {
		this.brand = brand;
		return this;
	}

	public String getPriceOf50kgBag() {
		return priceOf50kgBag;
	}

	public WholeSaleStockedBrandLocal setPriceOf50kgBag(String priceOf50kgBag) {
		this.priceOf50kgBag = priceOf50kgBag;
		return this;
	}

	public String getPriceOf24kgBale() {
		return priceOf24kgBale;
	}

	public WholeSaleStockedBrandLocal setPriceOf24kgBale(String priceOf24kgBale) {
		this.priceOf24kgBale = priceOf24kgBale;
		return this;
	}

	public String getPriceOf20kgBale() {
		return priceOf20kgBale;
	}

	public WholeSaleStockedBrandLocal setPriceOf20kgBale(String priceOf20kgBale) {
		this.priceOf20kgBale = priceOf20kgBale;
		return this;
	}
}
