package co.ke.bsl.pojo;

// Generated Dec 15, 2015 12:42:43 PM by Hibernate Tools 4.3.1

import org.idempiere.webservice.client.base.LoginRequest;

/**
 * Agents generated by hbm2java
 */

public class WholeSaleImportedStockedSugar implements java.io.Serializable {

	private String c_country_id;
	private String priceOf50kgBag;
	private String priceOf24kgBale;
	private String priceOf20kgBale;
	private String shopID;


	public String  localID;

	public String getLocalID() {
		return localID;
	}

	public void setLocalID(String localID) {
		this.localID = localID;
	}

	public String getShopID() {
		return shopID;
	}

	public void setShopID(String shopID) {
		this.shopID = shopID;
	}

	private LoginRequest loginRequest;

	private String AFA_SD_SGR_Surveyshops_ID;

	private String serverRecordID;


	public String getServerRecordID() {
		return serverRecordID;
	}

	public void setServerRecordID(String serverRecordID) {
		this.serverRecordID = serverRecordID;
	}


	private String serviceType="CreateWholesaleStockingPricesRangeImport";

	public LoginRequest getLoginRequest() {
		return loginRequest;
	}

	public void setLoginRequest(LoginRequest loginRequest) {
		this.loginRequest = loginRequest;
	}

	public String getAFA_SD_SGR_Surveyshops_ID() {
		return AFA_SD_SGR_Surveyshops_ID;
	}

	public void setAFA_SD_SGR_Surveyshops_ID(String AFA_SD_SGR_Surveyshops_ID) {
		this.AFA_SD_SGR_Surveyshops_ID = AFA_SD_SGR_Surveyshops_ID;
	}

	public String getServiceType() {
		return serviceType;
	}

	public void setServiceType(String serviceType) {
		this.serviceType = serviceType;
	}

	public String getC_country_id() {
		return c_country_id;
	}

	public WholeSaleImportedStockedSugar setC_country_id(String c_country_id) {
		this.c_country_id = c_country_id;
		return this;
	}

	public String getPriceOf50kgBag() {
		return priceOf50kgBag;
	}

	public WholeSaleImportedStockedSugar setPriceOf50kgBag(String priceOf50kgBag) {
		this.priceOf50kgBag = priceOf50kgBag;
		return this;
	}

	public String getPriceOf24kgBale() {
		return priceOf24kgBale;
	}

	public WholeSaleImportedStockedSugar setPriceOf24kgBale(String priceOf24kgBale) {
		this.priceOf24kgBale = priceOf24kgBale;
		return this;
	}

	public String getPriceOf20kgBale() {
		return priceOf20kgBale;
	}

	public WholeSaleImportedStockedSugar setPriceOf20kgBale(String priceOf20kgBale) {
		this.priceOf20kgBale = priceOf20kgBale;
		return this;
	}
}
