package co.ke.bsl.pojo;

// Generated Dec 15, 2015 12:42:43 PM by Hibernate Tools 4.3.1

import org.idempiere.webservice.client.base.LoginRequest;

/**
 * Agents generated by hbm2java
 */

	public class WholeSaleBrandLocal implements java.io.Serializable {

	private String AFA_SD_SGR_Surveyshops_ID;
	private String brand;
	private String priceOfFiftykgBag;
	private String priceOfTwentyFOurkgBale;
	private String priceOfTwentykgBale;

	private String shopID="0";

    public String  localID;

    public String getLocalID() {
        return localID;
    }

    public void setLocalID(String localID) {
        this.localID = localID;
    }

    public String getShopID() {
		return shopID;
	}

	public void setShopID(String shopID) {
		this.shopID = shopID;
	}


	private String serverRecordID;

	private LoginRequest loginRequest;

	private String serviceType="CreateWholesaleSugarPricesRangeLocal";


	public String getServerRecordID() {
		return serverRecordID;
	}

	public void setServerRecordID(String serverRecordID) {
		this.serverRecordID = serverRecordID;
	}

	public String getAFA_SD_SGR_Surveyshops_ID() {
		return AFA_SD_SGR_Surveyshops_ID;
	}

	public void setAFA_SD_SGR_Surveyshops_ID(String AFA_SD_SGR_Surveyshops_ID) {
		this.AFA_SD_SGR_Surveyshops_ID = AFA_SD_SGR_Surveyshops_ID;
	}

	public LoginRequest getLoginRequest() {
		return loginRequest;
	}

	public void setLoginRequest(LoginRequest loginRequest) {
		this.loginRequest = loginRequest;
	}

	public String getServiceType() {
		return serviceType;
	}

	public void setServiceType(String serviceType) {
		this.serviceType = serviceType;
	}

	/**
	 * @return the brand
	 */
	public String getBrand() {
		return brand;
	}

	/**
	 * @param brand the brand to set
	 */
	public void setBrand(String brand) {
		this.brand = brand;
	}

	/**
	 * @return the priceOfFiftykgBag
	 */
	public String getPriceOfFiftykgBag() {
		return priceOfFiftykgBag;
	}

	/**
	 * @param priceOfFiftykgBag the priceOfFiftykgBag to set
	 */
	public void setPriceOfFiftykgBag(String priceOfFiftykgBag) {
		this.priceOfFiftykgBag = priceOfFiftykgBag;
	}

	/**
	 * @return the priceOfTwentyFOurkgBale
	 */
	public String getPriceOfTwentyFOurkgBale() {
		return priceOfTwentyFOurkgBale;
	}

	/**
	 * @param priceOfTwentyFOurkgBale the priceOfTwentyFOurkgBale to set
	 */
	public void setPriceOfTwentyFOurkgBale(String priceOfTwentyFOurkgBale) {
		this.priceOfTwentyFOurkgBale = priceOfTwentyFOurkgBale;
	}

	/**
	 * @return the priceOfTwentykgBale
	 */
	public String getPriceOfTwentykgBale() {
		return priceOfTwentykgBale;
	}

	/**
	 * @param priceOfTwentykgBale the priceOfTwentykgBale to set
	 */
	public void setPriceOfTwentykgBale(String priceOfTwentykgBale) {
		this.priceOfTwentykgBale = priceOfTwentykgBale;
	}
}
